# RT-Thread building script for component
Import('RTT_ROOT')
Import('rtconfig')

from building import *

cwd = GetCurrentDir()
src = Glob('*.cpp')
src.extend(Glob('../../utils/utils.cpp'))

CPPPATH = [cwd]
CPPPATH = CPPPATH + ['../../utils']
PUBLIC_CPPPATH = ['../include']

LOCAL_CCFLAGS = ' -x c'
LOCAL_CCFLAGS += ' -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function'

group = DefineGroup('rga_slt', src, depend = ['RT_USING_RGA_SLT'], LOCAL_CPPPATH = CPPPATH, CPPPATH = PUBLIC_CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
